### ISSUE TITLE
Rename module to tf_aws_asg_lc

### ISSUE THREAD

**Issue by brandonjbjelland** [terraform-community-modules/tf_aws_asg_elb#7]
Though the module is designed to work in conjunction with an ELB created elsewhere in terraform, no ELB is created in this module. The focus of this repo is launch configuration and autoscaling groups. I understand it's a breaking change change to alter the repo name but I find the current name misleading and confusing. Any chance it could be adjusted to match the intent?

**Comment by antonbabenko** [comment]
Good point, I think the repo name stands for "ASG which works with ELB".

It will be rather breaking change for some people who rely on this module in first place and I am rather against such breaking changes.

Instead of renaming just this one we should come up with reasonable strategy for _naming_, _versioning_, _testing_, _coding standards_, _documentation_ in **most** of _terraform-community-modules_ to increase the quality
